version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run: mkdocs build --clean
      - persist_to_workspace:
          root: ~/project
          paths:
            - site

  deploy:
    executor: python/default
    steps:
      - attach_workspace:
          at: ~/project
      - run: pip install awscli
      - run:
          name: Sync and delete any old files from the S3 bucket.
          command: aws s3 sync site/ s3://$AWS_S3_BUCKET --acl public-read --cache-control "max-age=86400" --exclude "*.py*" --delete
      - run:
          name: Allow `awscli` to make requests to CloudFront.
          command: aws configure set preview.cloudfront true
      - run:
          name: Invalidate every object on CloudFront distribution.
          command: aws cloudfront create-invalidation --distribution-id $AWS_CF_DISTRIBUTION_ID --paths "/*"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
